/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfacelab2;

import Businesslab2.VitalSignHistory;
import Businesslab2.VitalSign;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author sanjalinagare
 */
public class ViewVitalJpanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewVitalJpanel
     */
    private VitalSignHistory vtsh;
    
        public ViewVitalJpanel(VitalSignHistory vtsh){
        initComponents();
        this.vtsh =vtsh;
        populateTable();
        
    }

    
public void populateTable()
{ 
        DefaultTableModel dtm = (DefaultTableModel)Table.getModel();
         dtm.setRowCount(0);

for(VitalSign vs: vtsh.getVitalSignList())//it is used for iteration 


{
    Object row[] =new Object[2];//Class
    row[0]=vs;
    row[1]=vs.getBloodPressure();
    dtm.addRow(row);


}
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeadingView = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        ViewBtn = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Temperature = new javax.swing.JLabel();
        BP = new javax.swing.JLabel();
        Pulse = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        TempTxt = new javax.swing.JTextField();
        BPTxt = new javax.swing.JTextField();
        PulseTxt = new javax.swing.JTextField();
        DateTxt = new javax.swing.JTextField();
        UpdateBtn = new javax.swing.JButton();
        Confirm = new javax.swing.JButton();

        HeadingView.setText("View Vital Sign");

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Date", "BloodPressure"
            }
        ));
        jScrollPane1.setViewportView(Table);

        ViewBtn.setText("View");
        ViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBtnActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Temperature.setText("Temperature");

        BP.setText("Blood Pressure");

        Pulse.setText("Pulse");

        Date.setText("Date");

        TempTxt.setEnabled(false);
        TempTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TempTxtActionPerformed(evt);
            }
        });

        BPTxt.setEnabled(false);

        PulseTxt.setEnabled(false);

        DateTxt.setEnabled(false);

        UpdateBtn.setText("Update");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        Confirm.setText("Confirm");
        Confirm.setEnabled(false);
        Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Confirm)
                .addGap(141, 141, 141))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(HeadingView, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Delete)
                            .addComponent(ViewBtn)
                            .addComponent(UpdateBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Temperature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BP, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                .addComponent(Pulse, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TempTxt)
                            .addComponent(BPTxt)
                            .addComponent(PulseTxt)
                            .addComponent(DateTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(HeadingView, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ViewBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UpdateBtn)))
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Temperature, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TempTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BP)
                    .addComponent(BPTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pulse)
                    .addComponent(PulseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Date)
                    .addComponent(DateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Confirm)
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBtnActionPerformed
        // TODO add your handling code here:

        int selectRow=Table.getSelectedRow();
        if(selectRow >=0)
        {
            VitalSign vs = (VitalSign)Table.getValueAt(selectRow, 0);
            
            BPTxt.setText(String.valueOf(vs.getBloodPressure()));
            TempTxt.setText(String.valueOf(vs.getTemprature()));
            PulseTxt.setText(String.valueOf(vs.getPulse()));
            DateTxt.setText(String.valueOf(vs.getDate()));
            
         
        }
        else
            JOptionPane.showMessageDialog(null,"No row to view ","Error",JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_ViewBtnActionPerformed

    private void TempTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TempTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TempTxtActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        int selectRow =Table.getSelectedRow();
        
        if(selectRow >=0){
            VitalSign vs =(VitalSign)Table.getValueAt(selectRow,0);
            vtsh.deletVitals(vs);
            JOptionPane.showMessageDialog(null, "Vital Sign deleted Successfully");
            populateTable();
            
        }
        else JOptionPane.showMessageDialog(null, "NO ROW TO DELETE","ERROR",JOptionPane.ERROR_MESSAGE);
        
        TempTxt.setText("");
       BPTxt.setText("");
       PulseTxt.setText("");
       DateTxt.setText("");
    }//GEN-LAST:event_DeleteActionPerformed

    private void ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmActionPerformed
        // TODO add your handling code here:
              // TODO add your handling code here:

        int selectRow = Table.getSelectedRow();
        
        if (selectRow>=0)
        {
           VitalSign vs =(VitalSign)Table.getValueAt(selectRow,0);
            vs.setTemprature(Double.parseDouble(TempTxt.getText()));
            vs.setDate(DateTxt.getText());
            vs.setBloodPressure(Double.parseDouble(BPTxt.getText()));
            vs.setPulse(Integer.parseInt(PulseTxt.getText()));
            
           JOptionPane.showMessageDialog(null, "Vital sign Updated successfully");
           populateTable();
           setFieldEnabled(false);
           Confirm.setEnabled(false);
           
        }
        else
           JOptionPane.showMessageDialog(null, "Please select a Row");
          TempTxt.setText("");
         BPTxt.setText("");
        PulseTxt.setText("");
         DateTxt.setText("");
    }//GEN-LAST:event_ConfirmActionPerformed

      private void setFieldEnabled(boolean b){
    TempTxt.setEnabled(b);
    BPTxt.setEnabled(b);
    PulseTxt.setEnabled(b);
    DateTxt.setEnabled(b);
      }
    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        // TODO add your handling code here:
            setFieldEnabled(true);
        Confirm.setEnabled(true);
        
        int selectRow = Table.getSelectedRow();
        
        if(selectRow >=0){
            VitalSign vs =(VitalSign)Table.getValueAt(selectRow, 0);
            TempTxt.setText(vs.getTemprature()+"");
            BPTxt.setText(vs.getBloodPressure()+"");
            PulseTxt.setText(vs.getPulse()+"");
            DateTxt.setText(vs.getDate());
        
           
        }
        else{
            JOptionPane.showMessageDialog(null, "Please Select a Row");
        }
        
       

             
    
    }//GEN-LAST:event_UpdateBtnActionPerformed
  
 
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BP;
    private javax.swing.JTextField BPTxt;
    private javax.swing.JButton Confirm;
    private javax.swing.JLabel Date;
    private javax.swing.JTextField DateTxt;
    private javax.swing.JButton Delete;
    private javax.swing.JLabel HeadingView;
    private javax.swing.JLabel Pulse;
    private javax.swing.JTextField PulseTxt;
    private javax.swing.JTable Table;
    private javax.swing.JTextField TempTxt;
    private javax.swing.JLabel Temperature;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JButton ViewBtn;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
