/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfacelab2;

import Businesslab2.VitalSignHistory;
import Businesslab2.VitalSign;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author sanjalinagare
 */
public class ViewVitalJpanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewVitalJpanel
     */
    private VitalSignHistory vtsh;
    
        public ViewVitalJpanel(VitalSignHistory vtsh){
        initComponents();
        this.vtsh =vtsh;
        populateTable();
        
    }

    
public void populateTable()
{ 
        DefaultTableModel dtm = (DefaultTableModel)Table.getModel();
         dtm.setRowCount(0);

for(VitalSign vs: vtsh.getVitalSignHistory())


{
Object row[] =new Object[2];
row[0]=vs;
row[1]=vs.getBloodPressure();
dtm.addRow(row);

}
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeadingView = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        ViewBtn = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Temperature = new javax.swing.JLabel();
        BP = new javax.swing.JLabel();
        Pulse = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        TempTxt = new javax.swing.JTextField();
        BPTxt = new javax.swing.JTextField();
        PulseTxt = new javax.swing.JTextField();
        DateTxt = new javax.swing.JTextField();

        HeadingView.setText("View Vital Sign");

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Date", "BloodPressure"
            }
        ));
        jScrollPane1.setViewportView(Table);

        ViewBtn.setText("View");
        ViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBtnActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Temperature.setText("Temperature");

        BP.setText("Blood Pressure");

        Pulse.setText("Pulse");

        Date.setText("Date");

        TempTxt.setEnabled(false);
        TempTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TempTxtActionPerformed(evt);
            }
        });

        BPTxt.setEnabled(false);

        PulseTxt.setEnabled(false);

        DateTxt.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(HeadingView, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(325, 325, 325)
                            .addComponent(ViewBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Delete))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(140, 140, 140)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Temperature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BP, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                .addComponent(Pulse, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TempTxt)
                            .addComponent(BPTxt)
                            .addComponent(PulseTxt)
                            .addComponent(DateTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(HeadingView, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewBtn)
                    .addComponent(Delete))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Temperature, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TempTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BP)
                    .addComponent(BPTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pulse)
                    .addComponent(PulseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Date)
                    .addComponent(DateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBtnActionPerformed
        // TODO add your handling code here:
        
        int selectRow=Table.getSelectedRow();
        if(selectRow >=0)
        {
            VitalSign vs = (VitalSign)Table.getValueAt(selectRow, 0);
            BPTxt.setText(String.valueOf(vs.getBloodPressure()));
            TempTxt.setText(String.valueOf(vs.getTemprature()));
            PulseTxt.setText(String.valueOf(vs.getPulse()));
            DateTxt.setText(String.valueOf(vs.getDate()));
            
         
        }
        else if (selectRow ==0)
            JOptionPane.showMessageDialog(null,"Please Select a Row ","Error",JOptionPane.ERROR_MESSAGE);
        else
            JOptionPane.showMessageDialog(null,"No row to view ","Error",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_ViewBtnActionPerformed

    private void TempTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TempTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TempTxtActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        int selectRow =Table.getSelectedRow();
        
        if(selectRow >=0){
            VitalSign vs =(VitalSign)Table.getValueAt(selectRow,0);
            vtsh.deletVitals(vs);
            JOptionPane.showMessageDialog(null, "Vital Sign deleted Successfully");
            populateTable();
            
        }
        else JOptionPane.showMessageDialog(null, "NO ROW TO DELETE","ERROR",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_DeleteActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BP;
    private javax.swing.JTextField BPTxt;
    private javax.swing.JLabel Date;
    private javax.swing.JTextField DateTxt;
    private javax.swing.JButton Delete;
    private javax.swing.JLabel HeadingView;
    private javax.swing.JLabel Pulse;
    private javax.swing.JTextField PulseTxt;
    private javax.swing.JTable Table;
    private javax.swing.JTextField TempTxt;
    private javax.swing.JLabel Temperature;
    private javax.swing.JButton ViewBtn;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
